//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRecepcionPesos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURACION
    {
        public int CON_ID { get; set; }
        public string CON_COMCAMIONERA { get; set; }
        public string CON_SERIALCAMIONERA { get; set; }
        public string CON_COMPISO { get; set; }
        public string CON_SERIALPISO { get; set; }
    }
}
