//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRecepcionPesos.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEcuamareEntities : DbContext
    {
        public DBEcuamareEntities()
            : base("name=DBEcuamareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONFIGURACION> CONFIGURACIONES { get; set; }
        public virtual DbSet<MATERIAL> MATERIALES { get; set; }
        public virtual DbSet<PERMISO> PERMISOS { get; set; }
        public virtual DbSet<PESO> PESOS { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDORES { get; set; }
        public virtual DbSet<TICKET> TICKETS { get; set; }
        public virtual DbSet<USUARIO> USUARIOS { get; set; }
        public virtual DbSet<V_TicketCompleto> V_TicketCompleto { get; set; }
        public virtual DbSet<V_TicketImprimir> V_TicketImprimir { get; set; }
    }
}
