//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRecepcionPesos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISO
    {
        public int USU_ID { get; set; }
        public int PER_ID { get; set; }
        public Nullable<bool> PER_ANULARTICKET { get; set; }
        public Nullable<bool> PER_USUARIOS { get; set; }
        public Nullable<bool> PER_CONFIGURACION { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
