//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRecepcionPesos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESO
    {
        public int PES_ID { get; set; }
        public Nullable<int> USU_ID { get; set; }
        public Nullable<int> TICK_ID { get; set; }
        public Nullable<System.DateTime> PES_FECHA { get; set; }
        public Nullable<float> PES_PESO { get; set; }
        public Nullable<int> PES_PORCENTAJE { get; set; }
        public Nullable<int> PES_TIPO { get; set; }
    
        public virtual TICKET TICKET { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
